import { AttendanceResponse } from "./type";

export const attendanceData: AttendanceResponse= {
    attendance_statement: [
      {
        subject_id: 10150,
        subject_pattern: "CORE",
        subject_code: "Hin",
        subject_name: "Hindi",
        subject_type: "TH",
        faculty: "Karthika S Nair, Sylvia Shanthi Mascarenhas",
        conducted: "78",
        attended: "76",
        absent: "2",
        exempt: "0",
        percentage: 97,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 97,
        final_percentage_remedial: 97,
        absent_dates: "21 Aug, 04 Sep",
        last_attended: "29/01/2024",
        shortage: "N",
        transfer_subject: "N",
        transfer_conducted_class: 2
      },
      {
        subject_id: 10131,
        subject_pattern: "CORE",
        subject_code: "Eng",
        subject_name: "English",
        subject_type: "TH",
        faculty: "Shiney Clifford, Sophronia G Maben",
        conducted: "78",
        attended: "76",
        absent: "2",
        exempt: "0",
        percentage: 97,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 97,
        final_percentage_remedial: 97,
        absent_dates: "04 Sep, 11 Sep",
        last_attended: "30/01/2024",
        shortage: "Y",
        transfer_subject: "N",
        transfer_conducted_class: -4
      },
      {
        subject_id: 10126,
        subject_pattern: "CORE",
        subject_code: "Chem",
        subject_name: "Chemistry",
        subject_type: "TH",
        faculty: "Karthik M Shenoy, Shravya P Shetty",
        conducted: "90",
        attended: "86",
        absent: "4",
        exempt: "0",
        percentage: 96,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 96,
        final_percentage_remedial: 96,
        absent_dates: "04 Sep, 21 Nov, 23 Dec",
        last_attended: "30/01/2024",
        shortage: "N",
        transfer_subject: "N",
        transfer_conducted_class: 8
      },
      {
        subject_id: 10136,
        subject_pattern: "CORE",
        subject_code: "Comp Sc",
        subject_name: "Computer Science",
        subject_type: "TH",
        faculty: "Mary. K F",
        conducted: "114",
        attended: "113",
        absent: "1",
        exempt: "0",
        percentage: 99,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 99,
        final_percentage_remedial: 99,
        absent_dates: "04 Sep",
        last_attended: "31/01/2024",
        shortage: "N",
        transfer_subject: "N",
        transfer_conducted_class: 0
      },
      {
        subject_id: 10128,
        subject_pattern: "CORE",
        subject_code: "Maths",
        subject_name: "Mathematics",
        subject_type: "TH",
        faculty: "Josma Nithisha Lobo, Vinitha Laveena D’Silva",
        conducted: "156",
        attended: "150",
        absent: "6",
        exempt: "0",
        percentage: 96,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 96,
        final_percentage_remedial: 96,
        absent_dates: "14 Jun, 18 Jul, 04 Sep, 11 Sep, 08 Dec, 31 Jan",
        last_attended: "31/01/2024",
        shortage: "N",
        transfer_subject: "N",
        transfer_conducted_class: 0
      },
      {
        subject_id: 10121,
        subject_pattern: "CORE",
        subject_code: "Phy",
        subject_name: "Physics",
        subject_type: "TH",
        faculty: "Avina Reshel D Souza, Veekshitha U",
        conducted: "152",
        attended: "138",
        absent: "14",
        exempt: "0",
        percentage: 91,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 91,
        final_percentage_remedial: 91,
        absent_dates: "04 Sep, 05 Sep, 11 Sep, 26 Sep, 08 Dec, 11 Dec, 12 Dec, 08 Jan, 29 Jan",
        last_attended: "30/01/2024",
        shortage: "N",
        transfer_subject: "N",
        transfer_conducted_class: -2
      },
      {
        subject_id: 7,
        subject_pattern: "MANDATORY",
        subject_code: "PCMC-12",
        subject_name: "Value Education",
        subject_type: "TH",
        faculty: "Veekshitha U",
        conducted: "11",
        attended: "11",
        absent: "0",
        exempt: "0",
        percentage: 100,
        excused: "0",
        remedial: "0",
        allowed: 0,
        final_percentage: 100,
        final_percentage_remedial: 100,
        absent_dates: null,
        last_attended: null,
        shortage: "N",
        transfer_subject: "N",
        transfer_conducted_class: 0
      }
    ],
    overall_percentage: 96
  };
  